micronaut:
  application:
    name: pi-tracker

pi-tracker:
  mqtt:
    host: tcp://${MQTT_HOST:127.0.0.1}
    port: ${MQTT_PORT:1883}
    client-id: ${MQTT_CLIENT_ID:piTracker}
    qos: ${MQTT_QOS:0}
    topic-prefix: ${MQTT_TOPIC_PREFIX:}